export const PAGE_PATH = {
    HOME: '/',
    SIGN_IN: '/auth/signin',
    DASH_BOARD: 'dashboard',
    CLUSTER: 'cluster',
    SUMMARY_QUERY: (id: string | number | undefined) => `summary/${id ?? ''}`,
    SUMMARY: 'summary',
    STATISTIC: 'statistic',
    SEARCH_TREND: 'search-trend',
    SEARCH_TERM_STATISTIC: 'search-term-statistic',
    SEARCH: 'search',
    POPULAR_TERMS: 'popular-terms',
    SUGGESTED_TERMS: 'suggested-terms',
    CATEGORY_BOOSTING: 'category-boosting',
    INDEX: 'index',
    SETTINGS: 'settings',
    MAPPINGS: 'mappings',
    MANAGEMENT: 'management',
    MANAGEMENT_QUERY: (param: number | string | undefined) =>
        `management/${param ?? '0'}`,
    DICTIONARY: 'dictionary',
    AUTOCOMPLETE: 'autocomplete',
    TYPO_CORRECTION: 'typo-correction',
    SYSTEM: 'system',
    USER_MANAGEMENT: 'user-management',
    NOT_FOUND: '*',
}
